import { scienceDeepStudyByLesson } from "./science-data";
export type DeepStudy = {
  title: string;
  paragraphs: string[];
  vocabulary: Array<[string, string, string]>;
  example: string;
  challenge: string;
};

const deep = (title: string, paragraphs: string[], vocabulary: Array<[string, string, string]>, example: string, challenge: string): DeepStudy => ({ title, paragraphs, vocabulary, example, challenge });

export const deepStudyByLesson: Record<string, DeepStudy> = {
  ...scienceDeepStudyByLesson,
  "math-meaning-multiplication": deep("Veja a multiplicação de três jeitos", ["A mesma situação pode aparecer como grupos iguais, adição repetida ou array. Quatro grupos de 6 são 6 + 6 + 6 + 6 e também 4 × 6 = 24.", "Em um array, as quantidades ficam organizadas em linhas e colunas com o mesmo número de objetos."], [["🧺","Equal groups","grupos com a mesma quantidade"],["✖️","Factors","números multiplicados"],["🎯","Product","resultado"]], "5 grupos de 4: 4 + 4 + 4 + 4 + 4 = 20.", "Desenhe um array que represente 24."),
  "math-facts": deep("Use padrões para construir fatos", ["A contagem 6, 12, 18, 24 mostra os múltiplos de 6 e ajuda a recuperar a tabuada.", "Um fato conhecido vira ponte: se você sabe 6 × 5 = 30, pode somar mais um grupo de 6 para descobrir 6 × 6 = 36."], [["🪜","Skip counting","saltos iguais"],["🔁","Multiples","resultados da tabuada"],["🧠","Known fact","fato que já sabemos"]], "6 × 6 = 6 × 5 + 6 = 36.", "Use 9 × 5 para descobrir 9 × 6."),
  "math-decompose": deep("Quebre números sem mudar o valor", ["Decompor é separar um número em partes mais fáceis, geralmente dezenas e unidades.", "Multiplique cada parte pelo outro número e depois some os dois resultados."], [["🧩","Break down","separar em partes"],["📦","Partial product","resultado de cada parte"],["🔢","Place value","valor da posição"]], "6 × 14 = (6 × 10) + (6 × 4) = 84.", "Resolva 7 × 23 separando 23 em 20 + 3."),
  "math-powers-ten": deep("Entenda o valor posicional", ["Multiplicar por 10 faz cada algarismo valer dez vezes mais; por 100, cem vezes mais.", "Pensar no deslocamento de valor é mais seguro do que apenas decorar que se acrescentam zeros."], [["1️⃣","× 1","mantém o número"],["🔟","× 10","dez vezes maior"],["💯","× 100","cem vezes maior"]], "32 → 32 × 10 = 320 → 32 × 100 = 3.200.", "Explique por que 205 × 10 = 2.050."),
  "math-algorithm": deep("Organize e confira o algoritmo", ["Escreva os números em colunas, com unidades embaixo de unidades e dezenas embaixo de dezenas.", "Multiplique da direita para a esquerda e reagrupe quando o resultado de uma casa passar de 9."], [["📏","Align","alinhar as casas"],["🎒","Regroup","trocar 10 unidades por 1 dezena"],["✅","Check","conferir o resultado"]], "38 × 6: 8 × 6 = 48; escreva 8 e reagrupe 4. Depois, 3 × 6 + 4 = 22. Resultado: 228.", "Organize em colunas e resolva 47 × 8."),
  "math-division-meaning": deep("Partilhar ou formar grupos?", ["Na partilha, sabemos quantos grupos haverá e procuramos quanto fica em cada um. No agrupamento, sabemos o tamanho e procuramos quantos grupos cabem.", "Em 24 ÷ 6 = 4, 24 é dividend, 6 é divisor e 4 é quotient. A multiplicação 6 × 4 = 24 confirma."], [["🎁","Dividend","total dividido"],["🧺","Divisor","número ou tamanho dos grupos"],["✅","Quotient","resultado"]], "24 cookies para 6 crianças = 4 para cada.", "Crie duas histórias diferentes para 20 ÷ 5."),
  "math-division-strategies": deep("Escolha uma representação", ["Arrays, saltos na reta e subtração repetida podem mostrar a mesma divisão.", "A família 7 × 8 = 56 também inclui 8 × 7, 56 ÷ 7 e 56 ÷ 8."], [["🔁","Inverse","operações que se desfazem"],["👨‍👩‍👧‍👦","Fact family","quatro fatos relacionados"],["➖","Repeated subtraction","retirar grupos"]], "20 ÷ 5 tem quatro saltos de 5 até 20.", "Escreva a família dos fatos 6, 9 e 54."),
  "math-long-division": deep("Repita um ciclo de passos", ["Descubra quantas vezes o divisor cabe na parte atual do dividendo, registre no quociente, multiplique e subtraia.", "Baixe o próximo algarismo e repita. Confira com divisor × quociente + resto."], [["➗","Divide","descobrir quantas vezes cabe"],["⬇️","Bring down","baixar algarismo"],["🧪","Check","confirmar o resultado"]], "Divide → multiply → subtract → bring down.", "Resolva 156 ÷ 12 e confira."),
  "math-remainders": deep("Entenda o que ficou", ["O remainder precisa ser menor que o divisor; caso contrário, ainda cabe outro grupo.", "Nos problemas do material, conte os grupos completos e observe o que sobra. Quando todos precisam de lugar em mesa, caixa ou equipe, pode ser necessário considerar mais um grupo completo."], [["🧩","Remainder","quantidade que sobra"],["📦","Complete group","grupo com a capacidade indicada"],["✅","Check","resto menor que o divisor"]], "31 ÷ 6 = 5 R1, porque 6 × 5 = 30 e sobra 1.", "Divida 43 doces em saquinhos de 6 e indique o resto."),
  "math-bar-picto": deep("Leia antes de calcular", ["Comece por título, categorias, eixos e intervalo da escala.", "No pictograph, cada símbolo completo vale o número indicado pela key."], [["🏷️","Label","nome de eixo ou categoria"],["📐","Scale","valor entre marcas"],["🔑","Key","valor de cada símbolo"]], "Se ★ = 4 livros, 3 estrelas = 12 livros.", "Se 🍎 = 5 maçãs, quanto valem 4 símbolos?"),
  "math-line-pie": deep("Cada gráfico conta uma história", ["Line graphs mostram mudanças no tempo: subidas, descidas e trechos estáveis.", "Pie charts mostram partes de um todo; metade é 1/2 ou 50%, e todas as partes formam 100%."], [["📈","Trend","direção da mudança"],["⭕","Whole","total representado"],["↕️","Range","maior menos menor"]], "Se o maior é 42 e o menor é 17, range = 25.", "Qual gráfico mostra melhor temperaturas de cinco dias?"),
  "math-time": deep("Ponteiros e linha do tempo", ["Cada número percorrido pelo minute hand vale 5 minutos; o hour hand se move aos poucos.", "Até 30 minutos usamos past; depois podemos contar quanto falta com to. Para duração, faça saltos até horas fáceis."], [["🕒","Quarter past","15 minutos depois"],["🕕","Half past","30 minutos depois"],["⏳","Elapsed time","tempo que passou"]], "9:35 → 10:00 = 25 min; → 10:20 = 20; total 45.", "Desenhe 5:40 e escreva usando to."),
  "ela-story-elements": deep("Monte o mapa da história", ["Setting reúne where e when; characters são quem participa; plot é a sequência dos eventos importantes.", "A solution responde ao problema principal e pode mostrar o que a personagem aprendeu ou como mudou."], [["🗺️","Setting","lugar e tempo"],["🎬","Plot","eventos importantes"],["🔓","Solution","resolução do problema"]], "Library + rainy Tuesday → missing key → clues → key found.", "Mapeie uma história: setting, character, problem, events e solution."),
  "ela-character-traits": deep("Descreva as personagens com clareza", ["Physical traits mostram a aparência: cabelo, olhos, altura, corpo, pele e outras características visíveis.", "Personality traits mostram como a personagem se comporta, por exemplo brave, kind, curious, honest, patient ou selfish."], [["👀","Physical trait","aparência observável"],["💭","Personality trait","modo de agir"],["📝","Description","características em uma frase"]], "Lena has curly black hair and is honest.", "Descreva uma personagem com duas características físicas e duas de personalidade."),
  "ela-georgie": deep("Revise o livro pelas perguntas da escola", ["Em The Thing About Georgie, identifique os settings, os characters e os problems que aparecem na história.", "Depois, explique como os personagens resolvem os problemas, liste cinco eventos importantes e compare como Georgie, Jeanie e Andy mudam ao longo do tempo."], [["🗺️","Settings","lugares e tempos da história"],["🧩","Problems and solutions","dificuldades e resoluções"],["🌱","Character change","mudança ao longo da trama"]], "Setting → characters → problem → solution → important events → changes.", "Escolha um dos três personagens e explique uma mudança ao longo do livro."),
  "ela-5w1h": deep("Faça seis perguntas ao texto", ["Who identifica pessoas; what, o evento; when e where, tempo e lugar.", "Why explica razão ou motivação; how mostra o modo. As seis respostas formam uma base para o summary."], [["👤","Who","quem participou"],["💡","Why","razão"],["🛠️","How","modo ou processo"]], "At the park = where; by following the map = how.", "Responda aos 5Ws e 1H de uma cena."),
  "ela-chronology": deep("Reconstrua a sequência", ["Chronological order organiza os acontecimentos do mais antigo para o mais recente.", "Use os eventos importantes do texto e conecte-os com first, next, then e finally."], [["1️⃣","First","primeiro"],["➡️","Next / then","em seguida"],["🏁","Finally","por último"]], "First → next → then → finally.", "Organize quatro eventos e use sequence words."),
  "ela-summary": deep("Mantenha a espinha do texto", ["Encontre a main idea e selecione somente key details necessários para entendê-la.", "Um summary usa palavras próprias, ordem lógica e não inclui opinião, invenções ou detalhes decorativos."], [["🎯","Main idea","ideia central"],["🔑","Key detail","detalhe necessário"],["✂️","Concise","claro e sem excesso"]], "Problema + ação principal + resultado formam um bom começo.", "Resuma uma cena em três frases."),
  "ela-imagery": deep("Faça o leitor sentir a cena", ["Imagery usa palavras precisas ligadas a sight, sound, smell, taste e touch.", "Verbos fortes também criam imagem: creaked and slammed permite ouvir mais do que made a noise."], [["👁️","Sight","cor, forma e movimento"],["👂","Sound","volume e ruído"],["✋","Touch","textura e temperatura"]], "Warm cinnamon drifted from the crisp apple pie.", "Descreva chuva usando três sentidos."),
  "history-trade": deep("Comércio, interesses e ambiente", ["Entre 1500 e 1530, no Brasil Pré-Colonial, portugueses exploraram pau-brasil, ou ibirapitanga, usado como corante na Europa.", "Eles dependiam do conhecimento e trabalho indígena. A madeira ia para feitorias no litoral e depois aos navios. A retirada intensa devastou a Mata Atlântica e ameaçou a espécie."], [["🤝","Escambo","troca sem moeda"],["🏚️","Feitoria","armazém fortificado"],["🌳","Ibirapitanga","pau-brasil"]], "Conhecimento indígena → extração → feitoria → navio.", "Compare o interesse português e as necessidades indígenas."),
  "history-wildlife": deep("Da captura ilegal ao cuidado", ["O tráfico captura, transporta e vende animais sem autorização, causando sofrimento e desequilíbrio ambiental.", "O material cita cerca de 38 milhões retirados por ano. Apreendidos podem ir aos Cetas para identificação, triagem e cuidados."], [["🚫","Tráfico","comércio ilegal"],["🦜","Silvestre","animal da natureza"],["🏥","Cetas","centro de triagem"]], "Não comprar e comunicar a um adulto quebra a corrente ilegal.", "Liste dois danos ao animal e dois ao ecossistema."),
  "history-technology": deep("Possibilidades e desigualdades", ["Após a pandemia ser declarada em março de 2020, cresceram e-commerce, ensino a distância, trabalho remoto e atendimento on-line.", "A exclusão digital limita oportunidades. Povos indígenas usam tecnologia para estudar, comunicar-se em suas línguas e monitorar territórios sem perder identidade."], [["🛒","E-commerce","comércio pela internet"],["📵","Exclusão digital","falta de acesso ou condições"],["🛡️","Monitoramento","acompanhar o território"]], "Acesso só por celular pode limitar estudo e trabalho.", "Compare uma vantagem e um limite do estudo on-line."),
  "history-payments": deep("Do escambo ao pagamento digital", ["Escambo, dinheiro, cartões e meios digitais mostram uma transformação longa; as formas antigas e novas podem coexistir.", "Pix e aproximação tornam pagamentos rápidos, mas exigem conferir destinatário e valor e nunca compartilhar senhas ou códigos."], [["📱","Pix","pagamento pela internet"],["📡","Aproximação","comunicação sem inserir cartão"],["🔐","Segurança","proteger dados e senhas"]], "Escambo 🤝 → dinheiro 💵 → cartão 💳 → Pix 📱.", "Crie três regras para pagamentos digitais seguros."),
  "geography-sectors": deep("A viagem de um produto pelos três setores", ["No setor primário, trabalhadores obtêm recursos da natureza. No secundário, indústrias transformam esses recursos.", "O setor terciário faz produtos circularem e atende necessidades por comércio, transporte e outros serviços."], [["🌾","Primário","produz ou retira da natureza"],["🏭","Secundário","transforma matérias-primas"],["🛍️","Terciário","vende e presta serviços"]], "Leite no campo → queijo na indústria → venda no mercado.", "Classifique: agricultor, fábrica de tecidos, motorista e farmácia."),
  "geography-field-city": deep("Uma troca nos dois sentidos", ["Alimentos consumidos na cidade são produzidos no campo. Máquinas, ferramentas, fertilizantes e serviços usados no campo são produzidos ou oferecidos na cidade.", "Estradas e transportes conectam produtores e consumidores; sem eles, há perda, falta e desperdício."], [["🔄","Interdependência","dependência mútua"],["🚚","Circulação","movimento de produtos e pessoas"],["🏙️","Serviço","atividade que atende uma necessidade"]], "Sem estrada, o produtor perde a venda e a cidade fica sem leite.", "Dê dois exemplos do que cada espaço oferece ao outro."),
  "geography-materials": deep("Da natureza até a prateleira", ["Matéria-prima é a base de um produto; produto industrializado passou por transformação.", "A cadeia produtiva inclui obter, transportar, transformar, embalar, distribuir e vender."], [["🪵","Matéria-prima","base usada na fabricação"],["⚙️","Transformação","mudança do material"],["🔗","Cadeia produtiva","sequência de etapas"]], "Trigo → farinha → massa → pão → padaria.", "Monte a cadeia do algodão até uma camiseta."),
  "geography-origin": deep("Três origens e três extrativismos", ["Recursos animais vêm dos animais; vegetais, das plantas; minerais, do solo ou das rochas.", "Mel e cera são animais; madeira e látex, vegetais; ferro, areia e petróleo, minerais."], [["🐝","Animal","recurso produzido por animal"],["🌳","Vegetal","recurso vindo das plantas"],["⛰️","Mineral","recurso do solo ou das rochas"]], "Mel 🐝 • madeira 🌳 • areia ⛰️.", "Classifique: couro, algodão, petróleo, lã, granito e látex."),
  "geography-recycling": deep("Manter materiais em circulação", ["Reciclar é recuperar uma parte reutilizável e transformá-la em matéria-prima de um novo ciclo.", "Evitar desperdício e reutilizar também preservam água, energia e recursos naturais."], [["♻️","Reciclar","transformar resíduo em recurso"],["🔁","Reutilizar","usar novamente"],["🌍","Sustentabilidade","cuidar do presente e do futuro"]], "Papel usado → separação → nova matéria-prima → novo papel.", "Explique como reciclar papel pode poupar árvores."),
};
