import type { StudySubject } from "./curriculum-data";
import type { QuizQuestion } from "./quiz-data";

type Option = [string, string];
const associations: Record<string, string> = {
  "Setores da economia:1": "SETOR PRIMÁRIO", "Setores da economia:2": "SETOR SECUNDÁRIO", "Setores da economia:3": "SETOR TERCIÁRIO",
  "Campo e cidade:2": "INTERDEPENDÊNCIA", "Matéria-prima e produtos:1": "MATÉRIA-PRIMA", "Matéria-prima e produtos:2": "PRODUTO INDUSTRIALIZADO",
  "Origem e extrativismo:1": "ORIGEM ANIMAL", "Origem e extrativismo:2": "ORIGEM VEGETAL", "Origem e extrativismo:3": "ORIGEM MINERAL",
  "Reciclagem e responsabilidade:1": "RECICLAGEM",
};

const q = (id: number, topic: string, prompt: string, support: string, correctIndex: number, options: Option[]): QuizQuestion => {
  const letters = ["a", "b", "c", "d"];
  return { id, topic, prompt, support, ...(associations[`${topic}:${id}`] ? { format: "association" as const, concept: associations[`${topic}:${id}`] } : {}), correct: letters[correctIndex], options: options.map(([label, explanation], index) => ({ id: letters[index], label, explanation })) };
};

export const geographySectorsQuiz: QuizQuestion[] = [
  q(1, "Setores da economia", "Qual atividade pertence a este setor?", "Ele reúne atividades que retiram ou produzem recursos diretamente da natureza.", 0, [["Cultivar tomates", "Correto. Agricultura é uma atividade do setor primário."], ["Fabricar molho de tomate", "A fábrica transforma a matéria-prima: setor secundário."], ["Vender o molho no mercado", "A venda pertence ao setor terciário."], ["Entregar o produto", "O transporte é um serviço do setor terciário."]]),
  q(2, "Setores da economia", "Qual atividade pertence a este setor?", "Ele transforma matérias-primas em outros produtos.", 2, [["Criar vacas", "A pecuária pertence ao setor primário."], ["Atender em uma farmácia", "Atendimento e comércio pertencem ao terciário."], ["Produzir queijo em uma indústria", "Correto. A indústria transforma leite em queijo."], ["Plantar algodão", "O cultivo pertence ao setor primário."]]),
  q(3, "Setores da economia", "Qual atividade pertence a este setor?", "Ele reúne comércio e prestação de serviços.", 3, [["Extrair areia", "Extração é setor primário."], ["Colher trigo", "Agricultura é setor primário."], ["Fabricar pão", "Transformação é setor secundário."], ["Vender pão na padaria", "Correto. A venda pertence ao setor terciário."]]),
  q(4, "Setores da economia", "João cultiva tomates, Ana fabrica brinquedos e Pedro atende em uma farmácia. Qual é a ordem dos setores?", "Classifique produzir, transformar e atender.", 1, [["Secundário, terciário e primário", "A ordem não corresponde às atividades."], ["Primário, secundário e terciário", "Correto. Cultivar, fabricar e atender seguem essa ordem."], ["Terciário, primário e secundário", "Cultivar não pertence ao terciário."], ["Primário, terciário e secundário", "Fabricar pertence ao secundário."]]),
  q(5, "Setores da economia", "Por que os três setores dependem uns dos outros?", "Pense em recurso natural, transformação e venda.", 2, [["Todos fazem o mesmo trabalho", "Eles cumprem funções diferentes."], ["Só o terciário produz alimentos", "A produção começa no primário."], ["Matérias-primas são produzidas, transformadas, transportadas e vendidas", "Correto. Cada setor participa de uma etapa."], ["Indústrias não usam matérias-primas", "Indústrias dependem delas."]]),
];

export const geographyFieldCityQuiz: QuizQuestion[] = [
  q(1, "Campo e cidade", "Como campo e cidade estão ligados?", "Um fornece produtos; o outro concentra indústrias, comércio e serviços.", 1, [["Não possuem relação", "Os dois espaços dependem um do outro."], ["Trocam produtos, matérias-primas, serviços e tecnologias", "Correto. Eles se completam."], ["Somente a cidade ajuda o campo", "A relação ocorre nos dois sentidos."], ["Somente o campo ajuda a cidade", "A cidade também oferece serviços e produtos."]]),
  q(2, "Campo e cidade", "Qual frase explica melhor este conceito?", "Identifique a dependência nos dois sentidos.", 3, [["Campo e cidade nunca trocam produtos", "Existe circulação constante."], ["Todos precisam morar na cidade", "As pessoas vivem em diferentes espaços."], ["A cidade produz sozinha todas as matérias-primas", "Muitas vêm do campo."], ["A cidade depende dos alimentos do campo, e o campo depende dos serviços da cidade", "Correto. Essa é a interdependência."]]),
  q(3, "Campo e cidade", "Se nenhum caminhão saísse do campo durante uma semana, o que poderia acontecer na cidade?", "Pense nos alimentos consumidos diariamente.", 0, [["Poderia faltar alimento fresco nos mercados", "Correto. O transporte conecta produção e consumo."], ["Plantações cresceriam nos mercados", "Mercados não substituem o campo."], ["Nada mudaria", "A cidade depende desse abastecimento."], ["Hospitais deixariam de existir", "Não é o efeito direto da situação."]]),
  q(4, "Campo e cidade", "Uma fazenda produz leite, mas não há estrada para levá-lo à cidade. Quem é prejudicado?", "Considere quem vende e quem consome.", 2, [["Apenas o fazendeiro", "Consumidores também ficam sem o produto."], ["Apenas as pessoas da cidade", "O produtor também perde."], ["O fazendeiro e as pessoas da cidade", "Correto. Um perde renda e os outros, o leite."], ["Ninguém", "A ligação foi interrompida."]]),
  q(5, "Campo e cidade", "O que a cidade pode oferecer a quem vive no campo?", "O texto cita serviços concentrados em áreas urbanas.", 1, [["Somente frutas e verduras", "Esses produtos geralmente vêm do campo."], ["Hospitais, bancos, escolas, máquinas e fertilizantes", "Correto. Serviços e produtos urbanos apoiam o campo."], ["Apenas solo e rios", "Não são serviços urbanos."], ["Somente animais", "Criação é típica do campo."]]),
];

export const geographyMaterialsQuiz: QuizQuestion[] = [
  q(1, "Matéria-prima e produtos", "Qual definição combina com este conceito?", "Ela é a base usada para fabricar outro produto.", 2, [["Um serviço", "Serviço não é base material."], ["Um produto já vendido", "A venda ocorre depois."], ["Material usado para produzir outro objeto ou alimento", "Correto. Trigo, madeira e leite são exemplos."], ["Qualquer embalagem vazia", "Isso não define matéria-prima."]]),
  q(2, "Matéria-prima e produtos", "Qual exemplo combina com este conceito?", "Ele passou por transformação.", 1, [["Trigo colhido", "Trigo é matéria-prima."], ["Pão feito com farinha", "Correto. O pão passou por transformação."], ["Árvore na floresta", "A árvore fornece matéria-prima."], ["Leite retirado da vaca", "O leite pode ser matéria-prima."]]),
  q(3, "Matéria-prima e produtos", "Qual é a principal matéria-prima de uma camiseta de algodão?", "O nome da fibra aparece no produto.", 3, [["Areia", "Areia é usada no vidro."], ["Leite", "Leite pode virar queijo."], ["Madeira", "Madeira pode virar papel ou móvel."], ["Algodão", "Correto. A fibra vira fio e tecido."]]),
  q(4, "Matéria-prima e produtos", "Qual sequência mostra corretamente a produção do pão?", "Organize do cultivo até a venda.", 0, [["Trigo plantado e colhido → farinha → pão → venda", "Correto. A sequência acompanha toda a cadeia."], ["Venda → trigo → farinha → pão", "A venda é a última etapa."], ["Farinha → venda → trigo → pão", "O trigo vem antes da farinha."], ["Pão → trigo → farinha → venda", "A matéria-prima vem primeiro."]]),
  q(5, "Matéria-prima e produtos", "Qual associação está correta?", "Pense na principal base de cada produto.", 1, [["Garrafa de vidro — leite", "Vidro vem principalmente da areia."], ["Mesa — madeira", "Correto."], ["Queijo — algodão", "Queijo vem do leite."], ["Papel — areia", "Papel vem principalmente da madeira."]]),
];

export const geographyOriginQuiz: QuizQuestion[] = [
  q(1, "Origem e extrativismo", "Qual matéria-prima pertence a esta origem?", "Ela é produzida ou retirada de animais.", 0, [["Leite", "Correto. O leite tem origem animal."], ["Madeira", "Origem vegetal."], ["Areia", "Origem mineral."], ["Algodão", "Origem vegetal."]]),
  q(2, "Origem e extrativismo", "Qual matéria-prima pertence a esta origem?", "Ela vem das plantas.", 2, [["Ferro", "Origem mineral."], ["Mel", "Origem animal."], ["Madeira", "Correto. Vem das árvores."], ["Sal", "Recurso mineral."]]),
  q(3, "Origem e extrativismo", "Qual recurso pertence a esta origem?", "Ele é retirado do solo ou das rochas.", 3, [["Cera de abelha", "Origem animal."], ["Látex", "Origem vegetal."], ["Castanha", "Origem vegetal."], ["Granito", "Correto. É uma rocha."]]),
  q(4, "Origem e extrativismo", "O que é extrativismo?", "A atividade retira recursos que já existem na natureza.", 1, [["Somente fabricar produtos", "A indústria transforma matérias-primas."], ["Retirar recursos da natureza para atender necessidades", "Correto. Pode ser animal, vegetal ou mineral."], ["Apenas vender em lojas", "Isso é comércio."], ["Plantar em uma fazenda", "Isso é agricultura."]]),
  q(5, "Origem e extrativismo", "Qual grupo está correto na ordem animal, vegetal e mineral?", "Confira as três origens.", 2, [["Ouro, mel e madeira", "Ouro é mineral."], ["Madeira, ferro e mel", "Madeira é vegetal."], ["Mel, látex e petróleo", "Correto."], ["Areia, cera e castanha", "Areia é mineral."]]),
];

export const geographyRecyclingQuiz: QuizQuestion[] = [
  q(1, "Reciclagem e responsabilidade", "Qual ação representa este conceito?", "Ela recupera a parte reutilizável e a recoloca na produção.", 1, [["Misturar todos os resíduos", "Isso dificulta o reaproveitamento."], ["Transformar papel usado em matéria-prima para novo papel", "Correto. Um novo ciclo é criado."], ["Retirar mais árvores sem necessidade", "Isso aumenta o consumo de recursos."], ["Desperdiçar água e alimentos", "Desperdício não é reciclagem."]]),
  q(2, "Reciclagem e responsabilidade", "Como a reciclagem diminui o uso de novas matérias-primas?", "Pense no material que volta a ser aproveitado.", 3, [["Faz produtos desaparecerem", "Os materiais são recuperados."], ["Aumenta o desperdício", "O objetivo é reduzi-lo."], ["Impede a produção", "Ela fornece material à produção."], ["Reaproveita resíduos para fabricar novos produtos", "Correto. Isso reduz a retirada de recursos."]]),
  q(3, "Reciclagem e responsabilidade", "Por que evitar desperdício de papel, madeira, água e alimentos?", "Todos dependem de recursos e trabalho.", 0, [["Para conservar recursos e reduzir impactos", "Correto."], ["Porque nunca podem ser usados", "Eles são úteis; o problema é desperdiçar."], ["Para produzir mais lixo", "O objetivo é produzir menos."], ["Porque só a cidade precisa deles", "Campo e cidade dependem deles."]]),
  q(4, "Reciclagem e responsabilidade", "Por que o extrativismo deve ser responsável?", "Recursos e habitats podem acabar ou ser prejudicados.", 2, [["Para retirar tudo rapidamente", "Isso ameaça a natureza."], ["Porque recursos são infinitos", "Muitos podem se esgotar."], ["Para atender necessidades sem destruir ambientes e comprometer o futuro", "Correto."], ["Para impedir qualquer uso da natureza", "O material propõe uso consciente."]]),
  q(5, "Reciclagem e responsabilidade", "Se todas as árvores fossem retiradas e nenhuma replantada, o que poderia acontecer?", "Considere animais e produtos vegetais.", 1, [["A floresta ficaria protegida", "Ela perderia abrigo e equilíbrio."], ["Animais perderiam habitat e faltariam madeira e frutos", "Correto."], ["A madeira aumentaria para sempre", "Sem novas árvores, acabaria."], ["Nada mudaria", "Muitas relações seriam afetadas."]]),
];

export const geographyGeneralQuiz = [...geographySectorsQuiz.slice(0, 4), ...geographyFieldCityQuiz.slice(0, 4), ...geographyMaterialsQuiz.slice(0, 4), ...geographyOriginQuiz.slice(0, 4), ...geographyRecyclingQuiz.slice(0, 4)].map((item, index) => ({ ...item, id: index + 1 }));

export const geographySubject: StudySubject = {
  key: "geography", name: "Geografia", icon: "🌎", eyebrow: "GEOGRAFIA • II TRIMESTRE", title: "Do campo ao produto",
  description: "Entenda os setores da economia, a ligação entre campo e cidade e o caminho das matérias-primas até os produtos.", assessmentDate: "Revisão livre", quizId: "geography-general",
  lessons: [
    { id: "geography-sectors", number: "01", icon: "🏭", title: "Setores da economia", subtitle: "Primário, secundário e terciário", quizId: "geography-sectors", intro: "As atividades econômicas são organizadas em três setores. Eles mostram como os recursos são obtidos, transformados e disponibilizados às pessoas.", facts: [{ term: "Setor primário", text: "obtém recursos diretamente da natureza por agricultura, pecuária, pesca e extrativismo." }, { term: "Setor secundário", text: "transforma matérias-primas em produtos nas indústrias e fábricas." }, { term: "Setor terciário", text: "reúne comércio e serviços, como lojas, farmácias, bancos, escolas, transporte e hospitais." }, { term: "Os setores se conectam", text: "o leite é produzido no campo, transformado em queijo e vendido no mercado." }], remember: "Primário retira ou produz; secundário transforma; terciário vende ou presta serviços.", tone: "mint" },
    { id: "geography-field-city", number: "02", icon: "🚜", title: "Campo e cidade", subtitle: "Espaços diferentes que se completam", quizId: "geography-field-city", intro: "Campo e cidade têm características próprias, mas são interdependentes. Produtos, pessoas, serviços, máquinas e matérias-primas circulam entre os dois espaços.", facts: [{ term: "O campo oferece", text: "alimentos e matérias-primas, como frutas, verduras, leite, algodão e madeira." }, { term: "A cidade oferece", text: "comércio, hospitais, bancos, escolas, indústrias, máquinas, insumos e fertilizantes." }, { term: "Transporte", text: "estradas e caminhões conectam produção, transformação, venda e consumo." }, { term: "Interdependência", text: "significa depender um do outro; se uma etapa falha, todos podem ser prejudicados." }], remember: "A cidade depende do campo, e o campo também depende da cidade.", tone: "blue" },
    { id: "geography-materials", number: "03", icon: "🧵", title: "Do que são feitos os produtos?", subtitle: "Matéria-prima, transformação e cadeia produtiva", quizId: "geography-materials", intro: "Matéria-prima é a base usada para fabricar um produto. Quando transformada pelo trabalho ou por máquinas, pode originar um produto industrializado.", facts: [{ term: "Trigo → pão", text: "o trigo é colhido, vira farinha, é usado no pão e depois vendido." }, { term: "Madeira → papel e móveis", text: "a madeira é processada para adquirir novas formas e usos." }, { term: "Algodão → camiseta", text: "a fibra vira fio, tecido e roupa." }, { term: "Areia → vidro", text: "a areia é aquecida e transformada em vidro para garrafas e espelhos." }, { term: "Leite → queijo", text: "o leite passa por etapas até se tornar queijo." }], remember: "Cadeia produtiva é a sequência desde a matéria-prima até a venda.", tone: "orange" },
    { id: "geography-origin", number: "04", icon: "🌱", title: "Qual é a origem?", subtitle: "Animal, vegetal, mineral e extrativismo", quizId: "geography-origin", intro: "As matérias-primas vêm da natureza e podem ter origem animal, vegetal ou mineral. Extrativismo é retirar recursos naturais para atender às necessidades das pessoas.", facts: [{ term: "Origem animal", text: "inclui leite, mel, cera, couro e lã." }, { term: "Origem vegetal", text: "inclui madeira, algodão, látex, açaí, castanhas e ervas." }, { term: "Origem mineral", text: "inclui ferro, ouro, areia, granito, petróleo e sal." }, { term: "Extrativismo responsável", text: "retira recursos respeitando a natureza e seus ritmos de renovação." }], remember: "Pergunte: veio de um animal, de uma planta ou do solo e das rochas?", tone: "purple" },
    { id: "geography-recycling", number: "05", icon: "♻️", title: "Reciclagem e uso responsável", subtitle: "Cuidar dos recursos naturais", quizId: "geography-recycling", intro: "Reciclar é recuperar a parte reutilizável de produtos consumidos para recolocá-la na produção ou criar novos objetos. Isso reduz lixo e o uso de novas matérias-primas.", facts: [{ term: "Separar resíduos", text: "facilita o encaminhamento e o reaproveitamento." }, { term: "Evitar desperdício", text: "economiza água, alimentos, papel, madeira, energia e trabalho." }, { term: "Novo ciclo", text: "um material usado pode voltar a ser matéria-prima." }, { term: "Sustentabilidade", text: "é cuidar das necessidades atuais sem comprometer as futuras." }], remember: "Reduzir, reutilizar e reciclar preserva recursos naturais.", tone: "sunny" },
  ],
};
