import type { QuizQuestion } from "./quiz-data";
import type { StudySubject } from "./curriculum-data";

const q = (id: number, topic: string, prompt: string, support: string, correct: string, options: Array<[string, string]>, concept?: string): QuizQuestion => ({
  id, topic, prompt, support, correct,
  ...(concept ? { format: "association", concept } : {}),
  options: options.map(([label, explanation], index) => ({ id: ["a", "b", "c", "d"][index], label, explanation })),
});

export const portugueseSubject: StudySubject = {
  key: "portuguese", name: "Português", icon: "📝", eyebrow: "PORTUGUÊS • REVISÃO", title: "Palavras, textos e atenção", description: "Revise os assuntos da prova com exemplos, desafios de associação e quiz.", assessmentDate: "Revisão livre", quizId: "portuguese-general",
  lessons: [
    { id: "pt-interview", number: "01", icon: "🎤", title: "Entrevista", subtitle: "Perguntas, respostas e participantes", intro: "Entrevista é uma conversa em que alguém pergunta e outra pessoa responde para informar ou conhecer opiniões.", facts: [{ term: "Entrevistador", text: "faz as perguntas." }, { term: "Entrevistado", text: "responde às perguntas." }, { term: "Pista", text: "perguntas normalmente terminam com ponto de interrogação." }], remember: "Leia a pergunta com calma antes de procurar a resposta.", tone: "purple", quizId: "portuguese-general" },
    { id: "pt-nouns", number: "02", icon: "🧩", title: "Substantivos", subtitle: "Simples, composto, primitivo e derivado", intro: "Os substantivos nomeiam seres, lugares, objetos e ideias. Podemos observá-los por sua formação.", facts: [{ term: "Simples", text: "tem uma só palavra: flor." }, { term: "Composto", text: "junta duas palavras: guarda-chuva." }, { term: "Primitivo e derivado", text: "flor é primitivo; florista é derivado." }], remember: "Conte as palavras e pergunte se ela nasceu de outra palavra.", tone: "mint", quizId: "portuguese-general" },
    { id: "pt-relations", number: "03", icon: "↔️", title: "Sinônimos e antônimos", subtitle: "Ideias parecidas ou contrárias", intro: "Sinônimos têm sentido igual ou parecido. Antônimos mostram ideias opostas.", facts: [{ term: "Sinônimo", text: "feliz e alegre têm sentido parecido." }, { term: "Antônimo", text: "claro e escuro têm sentidos opostos." }, { term: "Frase", text: "o sentido da frase ajuda a escolher a palavra certa." }], remember: "Sinônimo aproxima; antônimo faz o contrário.", tone: "orange", quizId: "portuguese-general" },
    { id: "pt-similar", number: "04", icon: "🔎", title: "Palavras parecidas", subtitle: "Homônimas e parônimas", intro: "Algumas palavras parecem iguais ou muito parecidas. O sentido da frase resolve a dúvida.", facts: [{ term: "Homônimas", text: "banco pode ser assento ou instituição financeira." }, { term: "Parônimas", text: "cumprimento é saudação; comprimento é tamanho." }, { term: "Dica", text: "leia a frase inteira." }], remember: "Não escolha só pelo som: pense no sentido.", tone: "blue", quizId: "portuguese-general" },
    { id: "pt-spelling", number: "05", icon: "✏️", title: "Terminações", subtitle: "-isar, -izar, -esa e -eza", intro: "A escrita correta pede atenção à terminação e prática com palavras da mesma família.", facts: [{ term: "-isar", text: "pesquisar, analisar e avisar." }, { term: "-izar", text: "organizar, realizar e utilizar." }, { term: "-eza", text: "indica qualidade: beleza e gentileza." }], remember: "Escreva devagar e confira a terminação.", tone: "sunny", quizId: "portuguese-general" },
  ],
};

export const portugueseQuiz: QuizQuestion[] = [
  q(1, "Entrevista", "Quem faz as perguntas em uma entrevista?", "Associe o conceito à pessoa certa.", "a", [["Entrevistador", "Correto! O entrevistador pergunta."], ["Entrevistado", "O entrevistado responde."], ["Leitor", "O leitor acompanha o texto."], ["Personagem", "Nem toda entrevista tem personagem." ]], "ENTREVISTADOR"),
  q(2, "Entrevista", "Qual sinal geralmente aparece no fim de uma pergunta?", "Procure a pontuação que indica pergunta.", "c", [["Ponto final", "O ponto final fecha uma afirmação."], ["Vírgula", "A vírgula separa partes da frase."], ["Ponto de interrogação", "Correto! Ele indica pergunta."], ["Dois-pontos", "Podem anunciar uma fala ou lista." ]]),
  q(3, "Substantivos", "Qual palavra é um substantivo composto?", "Veja qual é formada por duas palavras.", "b", [["flor", "Tem apenas uma palavra."], ["guarda-chuva", "Correto! Guarda + chuva formam uma palavra composta."], ["livro", "Tem apenas uma palavra."], ["mar", "Tem apenas uma palavra." ]], "SUBSTANTIVO COMPOSTO"),
  q(4, "Substantivos", "Qual par mostra uma palavra primitiva e uma derivada?", "A derivada nasce de outra palavra.", "d", [["sol → sol", "Não há palavra derivada aqui."], ["mar → livro", "Uma não nasceu da outra."], ["flor → chuva", "Uma não nasceu da outra."], ["livro → livraria", "Correto! Livraria deriva de livro." ]], "PRIMITIVO → DERIVADO"),
  q(5, "Sinônimos", "Qual é sinônimo de feliz?", "Escolha uma palavra de sentido parecido.", "a", [["alegre", "Correto! Feliz e alegre têm sentido parecido."], ["triste", "Triste é antônimo de feliz."], ["escuro", "Não tem relação com feliz."], ["baixo", "Não tem relação com feliz." ]], "SINÔNIMO"),
  q(6, "Antônimos", "Qual é antônimo de claro?", "Escolha uma palavra de sentido contrário.", "c", [["brilhante", "É parecida com claro."], ["iluminado", "É parecida com claro."], ["escuro", "Correto! Escuro é o contrário de claro."], ["limpo", "Não é o contrário de claro." ]], "ANTÔNIMO"),
  q(7, "Homônimas", "Na frase “Sentei no banco da praça”, o que significa banco?", "Leia a frase inteira para descobrir o sentido.", "b", [["Instituição que guarda dinheiro", "A praça dá a pista de outro sentido."], ["Lugar para sentar", "Correto! É o banco da praça."], ["Uma profissão", "Não é profissão."], ["Um comprimento", "Não é medida." ]]),
  q(8, "Parônimas", "Complete: “Enviei um ____ à professora quando a vi.”", "Pense em saudação.", "a", [["cumprimento", "Correto! Cumprimento é saudação."], ["comprimento", "Comprimento é tamanho."], ["cumprir", "É um verbo."], ["comprimido", "É outra palavra." ]], "CUMPRIMENTO"),
  q(9, "Ortografia", "Qual palavra está escrita corretamente?", "Confira a terminação.", "d", [["pesquizar", "A forma correta é pesquisar."], ["organisar", "A forma correta é organizar."], ["belezaa", "A forma correta é beleza."], ["realizar", "Correto! Termina em -izar." ]]),
  q(10, "Ortografia", "Qual palavra indica uma qualidade?", "Escolha uma palavra terminada em -eza.", "b", [["princesa", "Princesa é um título."], ["gentileza", "Correto! Gentileza é uma qualidade."], ["duquesa", "Duquesa é um título."], ["francesa", "Indica origem/nacionalidade." ]]),
];
